steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/northern-union-322016/first_app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/northern-union-322016/first_app']
